name = "astrospacious"

# Pages build directory (required)
pages_build_output_dir = "./dist"

# KV bindings
[[kv_namespaces]]
binding = "topic-data"
id = "7644d9aa95af4930adcba0334a57f2f0"
preview_id = "7644d9aa95af4930adcba0334a57f2f0"
